# Configuration des paquets Fedora officiels
MODULE_NAME="Fedora Official Packages"

# Commande d'installation pour les paquets Fedora
INSTALL_CMD="dnf install -y"

# Prérequis (paquets nécessaires avant l'installation principale)
PREREQS=""

# Liste des paquets à installer depuis les dépôts Fedora
PACKAGES="

git
curl
wget

micro

btop
fastfetch


"
