# Configuration des applications Flatpak depuis Flathub
MODULE_NAME="Flathub Flatpak Applications"

# Commande d'installation pour les Flatpak
INSTALL_CMD="flatpak install -y flathub"

# Prérequis (activation de Flathub si nécessaire)
PREREQS=""

# Liste des applications Flatpak à installer depuis Flathub
PACKAGES="



"
