# Configuration des applications Flatpak depuis Flathub
MODULE_NAME="Flathub Flatpak Applications"

# Commande d'installation pour les Flatpak
INSTALL_CMD="flatpak install -y flathub"

# Prérequis (aucun - l'activation de Flathub se fait via la commande personnalisée ci-dessous)
PREREQS=""

# Liste des applications Flatpak à installer depuis Flathub
PACKAGES="

# Activation du dépôt Flathub (doit rester en premier)
flathub-setup|flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Ajoutez ici vos applications Flatpak (format: ID.Application.Flatpak)

com.bitwarden.desktop
com.discordapp.Discord
#dev.vencord.Vesktop
md.obsidian.Obsidian
com.usebottles.bottles:Bottles
#org.dupot.easyflatpak:EasyFlatpak
io.github.flattool.Warehouse:Warehouse
com.github.tchx84.Flatseal:Flatseal
io.github.giantpinkrobots.flatsweep:FlatSweep
io.github.kolunmi.Bazaar:Bazaar
io.github.dvlv.boxbuddyrs:Box Buddy
it.mijorus.gearlever:Gearlever
com.github.wwmm.easyeffects
#com.ktechpit.colorwall
#io.github.getnf.embellish
com.github.Murmele.Gittyup
be.alexandervanhee.gradia
org.localsend.localsend_app
org.gnome.World.PikaBackup
io.github.plrigaux.sysd-manager
com.github.unrud.VideoDownloader

"