# Configuration des paquets RPM Fusion
MODULE_NAME="RPM Fusion Packages"

# Commande d'installation pour les paquets RPM Fusion
INSTALL_CMD="dnf install -y"

# Prérequis (activation des dépôts RPM Fusion)
PREREQS="
https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-44.noarch.rpm
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-44.noarch.rpm
"

# Liste des paquets à installer depuis RPM Fusion
PACKAGES="



"
